name: Build and Deploy Next.js App

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AUTH_GOOGLE_ID: ${{ secrets.AUTH_GOOGLE_ID }}
      AUTH_GOOGLE_SECRET: ${{ secrets.AUTH_GOOGLE_SECRET }}
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Archive production artifacts
        run: tar -czf nextjs-app.tar.gz .next public package.json node_modules prisma

      - name: Copy files to EC2 using rsync
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: nextjs-app.tar.gz
          remote_path: ~/nextjs-app.tar.gz
          remote_host: ${{ secrets.EC2_HOST }}
          remote_user: ${{ secrets.EC2_USER }}
          remote_key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            set -e
            mkdir -p ~/nextjs-app
            tar -xzf ~/nextjs-app.tar.gz -C ~/nextjs-app
            cd ~/nextjs-app
            npm install --production
            npx prisma migrate deploy
            pm2 restart nextjs-app || pm2 start npm --name "nextjs-app" -- start
            sudo systemctl restart nginx
